### ISSUE TITLE
Errore compilazione

### ISSUE THREAD

**Issue by Sprechen** [italia/design-web-toolkit#122]
Ho clonato il progetto e ho provato a fare una build, con i seguenti comandi:
```
npm install
npm run build
```
Tuttavia, non riesco a completare la build, in quanto ho il seguente errore:
```
> design-web-toolkit@1.0.0-beta build /Users/luca/Downloads/design-web-toolkit-master
> npm-run-all build:resources build:css build:js build:styleguide


> design-web-toolkit@1.0.0-beta build:resources /Users/luca/Downloads/design-web-toolkit-master
> shx mkdir -p build/src && shx cp -r src/vendor build/ && shx cp -r src/icons build/src/icons && shx cp src/_preview.tmpl build/index.html


> design-web-toolkit@1.0.0-beta build:css /Users/luca/Downloads/design-web-toolkit-master
> suitcss -m -c .postcss.js index.css build/build.css


src/utils/zindex/index.css
16:16	⚠  Unexpected unit (length-zero-no-unit) [stylelint]


> design-web-toolkit@1.0.0-beta build:js /Users/luca/Downloads/design-web-toolkit-master
> cross-env WEBPACK_ENV=build webpack

Hash: 89a3fc1e8615a26f096e
Version: webpack 3.10.0
Time: 13289ms
                Asset     Size  Chunks             Chunk Names
           0.chunk.js    61 kB       0  [emitted]  
           1.chunk.js  69.3 kB       1  [emitted]  
           2.chunk.js  20.8 kB       2  [emitted]  
    styleguide.min.js  91.5 kB       3  [emitted]  styleguide
           IWT.min.js  91.4 kB       4  [emitted]  IWT
       0.chunk.js.map   313 kB       0  [emitted]  
       1.chunk.js.map   471 kB       1  [emitted]  
       2.chunk.js.map  61.7 kB       2  [emitted]  
styleguide.min.js.map   656 kB       3  [emitted]  styleguide
       IWT.min.js.map   656 kB       4  [emitted]  IWT
   [2] (webpack)/buildin/global.js 823 bytes {3} {4} [built]
   [4] ./src (.*)index\.js$ 733 bytes {3} {4} [built]
  [29] ./src/modules/header/index.js 4.64 kB {3} {4} [optional] [built]
  [31] ./src/scripts/index.js 428 bytes {3} {4} [optional] [built]
  [36] ./src/scripts/console.js 605 bytes {3} {4} [built]
  [37] ./src/scripts/ehnance.js 428 bytes {3} {4} [built]
  [38] ./src/scripts/scrollto.js 664 bytes {3} {4} [built]
  [39] ./src/scripts/focus.js 622 bytes {3} {4} [built]
  [47] ./index.js 1.35 kB {4} [built]
  [48] ./config.js 1.04 kB {4} [built]
  [49] ./theme/index-styleguide.js 1.23 kB {3} [built]
  [50] ./theme/config-styleguide.js 1.21 kB {3} [built]
  [56] (webpack)/buildin/module.js 521 bytes {1} [built]
  [57] ./node_modules/moment/locale it 181 bytes {1} [optional] [built]
    + 45 hidden modules

ERROR in ./node_modules/tablesaw/dist/tablesaw.jquery.js
Module build failed: Error: Couldn't find preset "@ava/stage-4" relative to directory "/Users/luca/Downloads/design-web-toolkit-master/node_modules/tablesaw"
    at /Users/luca/Downloads/design-web-toolkit-master/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
    at Array.map (native)
    at OptionManager.resolvePresets (/Users/luca/Downloads/design-web-toolkit-master/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/Users/luca/Downloads/design-web-toolkit-master/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/Users/luca/Downloads/design-web-toolkit-master/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/Users/luca/Downloads/design-web-toolkit-master/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/luca/Downloads/design-web-toolkit-master/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/Users/luca/Downloads/design-web-toolkit-master/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/Users/luca/Downloads/design-web-toolkit-master/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/luca/Downloads/design-web-toolkit-master/node_modules/babel-loader/lib/index.js:46:20)
    at Object.module.exports (/Users/luca/Downloads/design-web-toolkit-master/node_modules/babel-loader/lib/index.js:163:20)
 @ ./src/components/table/index.js 15:4-17:6
 @ ./src (.*)index\.js$
 @ ./theme/index-styleguide.js

npm ERR! Darwin 16.7.0
npm ERR! argv "/Users/luca/.nvm/versions/node/v7.7.2/bin/node" "/Users/luca/.nvm/versions/node/v7.7.2/lib/node_modules/npm/bin/npm-cli.js" "run" "build:js"
npm ERR! node v7.7.2
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! design-web-toolkit@1.0.0-beta build:js: `cross-env WEBPACK_ENV=build webpack`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the design-web-toolkit@1.0.0-beta build:js script 'cross-env WEBPACK_ENV=build webpack'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the design-web-toolkit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env WEBPACK_ENV=build webpack
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs design-web-toolkit
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls design-web-toolkit
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/luca/Downloads/design-web-toolkit-master/npm-debug.log
ERROR: "build:js" exited with 1.

npm ERR! Darwin 16.7.0
npm ERR! argv "/Users/luca/.nvm/versions/node/v7.7.2/bin/node" "/Users/luca/.nvm/versions/node/v7.7.2/bin/npm" "run" "build"
npm ERR! node v7.7.2
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! design-web-toolkit@1.0.0-beta build: `npm-run-all build:resources build:css build:js build:styleguide`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the design-web-toolkit@1.0.0-beta build script 'npm-run-all build:resources build:css build:js build:styleguide'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the design-web-toolkit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm-run-all build:resources build:css build:js build:styleguide
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs design-web-toolkit
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls design-web-toolkit
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/luca/Downloads/design-web-toolkit-master/npm-debug.log
```

avete qualche suggerimento?

**Comment by francescozaia** [comment]
Ciao @Sprechen, dovrebbe essere lo stesso problema segnalato recentemente #121
